

CREATE USER C##Five IDENTIFIED BY 1;
GRANT CREATE SESSION TO C##Five; 
GRANT CREATE TABLE TO C##Five; 
GRANT CREATE SEQUENCE TO C##Five; 
GRANT CREATE SYNONYM TO C##Five; 
GRANT CREATE PROCEDURE TO C##Five; 
GRANT CREATE TRIGGER TO C##Five; 
GRANT CREATE CLUSTER TO C##Five; 
GRANT CREATE TYPE TO C##Five; 
GRANT UNLIMITED TABLESPACE TO C##Five; 
ALTER USER C##Five QUOTA UNLIMITED ON SYSTEM;
